apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicuredeploy
  labels:
    app: medicure
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicurecontainer
        image: swapnadamodaran/medicure:v1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medicureservice
  labels:
    app: medicure
spec:
  selector:
    app: medicure

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
